services:
  - type: web
    name: sanitaryware-backend
    env: docker
    repo: https://github.com/bhumikajain54/sanitaryware
    rootDir: Backend
    plan: free
    region: oregon
    envVars:
      - key: DATASOURCE_URL
        sync: false
        placeholder: jdbc:mysql://mysql-2aff1a60-jainbhumika54-bdc3.j.aivencloud.com:21772/sanitaryware
      - key: DATASOURCE_USER
        sync: false
      - key: DATASOURCE_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: "*"
      - key: PORT
        value: "8080"
    healthCheckPath: /actuator/health
