services:
  - type: web
    name: sanitaryware-1
    env: docker
    repo: https://github.com/bhumikajain54/sanitaryware
    rootDir: .
    plan: free
    region: oregon
    envVars:
      - key: DATASOURCE_URL
        value: jdbc:postgresql://ep-broad-queen-aeecsanz-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: DATASOURCE_USER
        value: neondb_owner
      - key: DATASOURCE_PASSWORD
        value: npg_sd92hGqtkolx
      - key: FRONTEND_URL
        value: "*"
    healthCheckPath: /api/health/db
