services:
  - type: web
    name: sanitaryware-backend
    env: docker
    repo: https://github.com/bhumikajain54/sanitaryware
    rootDir: Backend
    plan: free
    region: oregon
    envVars:
      - key: DATASOURCE_URL
        value: jdbc:postgresql://ep-falling-glitter-aj7qi373-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: DATASOURCE_USER
        value: neondb_owner
      - key: DATASOURCE_PASSWORD
        value: npg_Ja7x0EgvMjwQ
      - key: FRONTEND_URL
        value: "*"
    healthCheckPath: /api/health/db
