import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Generate Invoice PDF for printing or downloading
 * @param {Object} invoice - Invoice data object
 * @param {string} mode - 'print' or 'download'
 */
export const generateInvoicePDF = (invoice, mode = 'download') => {
    try {
        // Create new PDF document
        const doc = new jsPDF();

        // Company Header
        doc.setFontSize(20);
        doc.setTextColor(13, 148, 136); // Teal color
        doc.text('INVOICE', 105, 20, { align: 'center' });

        // Invoice Details
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Invoice No: ${invoice.invoiceNo}`, 20, 40);
        doc.text(`Date: ${invoice.date}`, 20, 50);
        doc.text(`Customer: ${invoice.customer}`, 20, 60);

        // Status Badge
        doc.setFontSize(10);
        if (invoice.synced) {
            doc.setTextColor(34, 197, 94); // Green
            doc.text('✓ Synced to Tally', 150, 50);
        } else {
            doc.setTextColor(249, 115, 22); // Orange
            doc.text('⚠ Pending Sync', 150, 50);
        }

        // Line separator
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 70, 190, 70);

        // Invoice Items Table (if items exist)
        if (invoice.items && invoice.items.length > 0) {
            const tableData = invoice.items.map(item => [
                item.name || item.description,
                item.qty || item.quantity,
                `₹${item.rate || item.price}`,
                `${item.tax || item.gst}%`,
                `₹${((item.qty || item.quantity) * (item.rate || item.price) * (1 + (item.tax || item.gst) / 100)).toLocaleString()}`
            ]);

            doc.autoTable({
                startY: 80,
                head: [['Item', 'Qty', 'Rate', 'GST', 'Total']],
                body: tableData,
                theme: 'grid',
                headStyles: { fillColor: [13, 148, 136] },
                styles: { fontSize: 10 }
            });
        }

        // Total Amount
        const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 20 : 90;
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Total Amount:', 120, finalY);
        doc.setFontSize(16);
        doc.setTextColor(13, 148, 136);
        doc.text(invoice.total, 170, finalY);

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text('Generated by Sanitaryware Admin Panel', 105, 280, { align: 'center' });
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, 285, { align: 'center' });

        // Output based on mode
        if (mode === 'print') {
            // Open in new window for printing
            const pdfBlob = doc.output('blob');
            const pdfUrl = URL.createObjectURL(pdfBlob);
            const printWindow = window.open(pdfUrl, '_blank');
            if (printWindow) {
                printWindow.onload = () => {
                    printWindow.print();
                };
            }
        } else {
            // Download PDF
            doc.save(`Invoice_${invoice.invoiceNo}_${new Date().getTime()}.pdf`);
        }

        return true;
    } catch (error) {
        console.error('PDF Generation Error:', error);
        throw error;
    }
};

/**
 * Generate bulk invoices PDF
 * @param {Array} invoices - Array of invoice objects
 */
export const generateBulkInvoicesPDF = (invoices) => {
    try {
        const doc = new jsPDF();

        invoices.forEach((invoice, index) => {
            if (index > 0) {
                doc.addPage();
            }

            // Similar logic as single invoice
            doc.setFontSize(20);
            doc.setTextColor(13, 148, 136);
            doc.text('INVOICE', 105, 20, { align: 'center' });

            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`Invoice No: ${invoice.invoiceNo}`, 20, 40);
            doc.text(`Date: ${invoice.date}`, 20, 50);
            doc.text(`Customer: ${invoice.customer}`, 20, 60);

            doc.setFontSize(14);
            doc.text('Total Amount:', 120, 90);
            doc.setFontSize(16);
            doc.setTextColor(13, 148, 136);
            doc.text(invoice.total, 170, 90);
        });

        doc.save(`Bulk_Invoices_${new Date().getTime()}.pdf`);
        return true;
    } catch (error) {
        console.error('Bulk PDF Generation Error:', error);
        throw error;
    }
};

/**
 * Generate Product Catalog PDF for printing or downloading
 * @param {Array} products - Array of product objects
 */
export const generateProductListPDF = (products) => {
    try {
        const doc = new jsPDF();

        // Company Header
        doc.setFontSize(22);
        doc.setTextColor(13, 148, 136); // Teal color
        doc.text('PRODUCT CATALOG', 105, 20, { align: 'center' });

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 105, 28, { align: 'center' });

        // Line separator
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 35, 190, 35);

        // Products Table
        const tableData = products.map(p => [
            p.name,
            typeof p.brand === 'object' && p.brand ? p.brand.name : (p.brand || 'N/A'),
            typeof p.category === 'object' && p.category ? p.category.name : (p.category || 'N/A'),
            `₹${p.price}`,
            p.stock,
            p.status
        ]);

        doc.autoTable({
            startY: 45,
            head: [['Product Name', 'Brand', 'Category', 'Price', 'Stock', 'Status']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [13, 148, 136], fontStyle: 'bold' },
            styles: { fontSize: 8, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 50 },
                1: { cellWidth: 30 },
                2: { cellWidth: 30 },
                3: { cellWidth: 25, halign: 'right' },
                4: { cellWidth: 20, halign: 'center' },
                5: { cellWidth: 20, halign: 'center' }
            }
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
            doc.text('© Singhai Traders - Sanitaryware Collection', 105, 285, { align: 'center' });
        }

        doc.save(`Product_Catalog_${new Date().getTime()}.pdf`);
        return true;
    } catch (error) {
        console.error('Product PDF Generation Error:', error);
        throw error;
    }
};
